blueprint:
  name: "IKEA Bilresa Scroll Wheel – Lysstyrkestyring (flere lamper)"
  description: "Styr lysstyrke for én eller flere lamper med IKEA Bilresa scroll-hjul"
  domain: automation

  input:
    scrollwheel_right_event_entity:
      name: "Scroll-hjul hændelses-entity – Højredrejning"
      description: "Hændelses-entity for scroll-hjulet ved drejning mod højre"
      selector:
        entity:

    scrollwheel_left_event_entity:
      name: "Scroll-hjul hændelses-entity – Venstredrejning"
      description: "Hændelses-entity for scroll-hjulet ved drejning mod venstre"
      selector:
        entity:

    target_lights:
      name: "Lamper der skal styres"
      description: "Vælg én eller flere lamper"
      selector:
        target:
          entity:
            domain: light

    scroll_right_direction:
      name: "Handling ved højredrejning"
      description: "Hvad skal der ske ved drejning mod højre?"
      selector:
        select:
          options:
            - label: "Forøg lysstyrke"
              value: "brighten"
            - label: "Reducer lysstyrke"
              value: "dim"
      default: "brighten"

    scroll_left_direction:
      name: "Handling ved venstredrejning"
      description: "Hvad skal der ske ved drejning mod venstre?"
      selector:
        select:
          options:
            - label: "Forøg lysstyrke"
              value: "brighten"
            - label: "Reducer lysstyrke"
              value: "dim"
      default: "dim"

    brightness_per_step:
      name: "Lysstyrke pr. trin (%)"
      default: 5
      selector:
        number:
          min: 1
          max: 20

    startup_brightness:
      name: "Start-lysstyrke ved tænding (%)"
      default: 20
      selector:
        number:
          min: 5
          max: 50

trigger:
  - platform: state
    entity_id: !input scrollwheel_right_event_entity
    id: "højre"

  - platform: state
    entity_id: !input scrollwheel_left_event_entity
    id: "venstre"

action:
  - variables:
      er_højre: "{{ trigger.id == 'højre' }}"
      retning_højre: !input scroll_right_direction
      retning_venstre: !input scroll_left_direction
      lys_trin: !input brightness_per_step
      start_lys: !input startup_brightness

      # Bestem retning (+ / -)
      retning: >-
        {% if er_højre %}
          {{ 1 if retning_højre == 'brighten' else -1 }}
        {% else %}
          {{ 1 if retning_venstre == 'brighten' else -1 }}
        {% endif %}

      lys_ændring: "{{ lys_trin | int * retning }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ retning > 0 }}"
        sequence:
          # Forøg lysstyrke (tænd hvis slukket)
          - service: light.turn_on
            target: !input target_lights
            data:
              brightness_step_pct: "{{ lys_ændring }}"
              brightness_pct: "{{ start_lys }}"
    default:
      # Reducér lysstyrke
      - service: light.turn_on
        target: !input target_lights
        data:
          brightness_step_pct: "{{ lys_ændring }}"

mode: queued
max: 20


    startup_brightness_left:
