blueprint:
  name: "IKEA Bilresa Scroll Wheel – Lysstyrkestyring (Højre & Venstre, flere lamper)"
  description: "Styr lysstyrke for én eller flere lamper med IKEA Bilresa scroll-hjul. Separate indstillinger for højre- og venstredrejning."
  domain: automation

  input:
    scrollwheel_right_event_entity:
      name: "Scroll-hjul hændelses-entity – Højredrejning"
      description: "Hændelses-entity for scroll-hjulet ved drejning mod højre"
      selector:
        entity:

    scrollwheel_left_event_entity:
      name: "Scroll-hjul hændelses-entity – Venstredrejning"
      description: "Hændelses-entity for scroll-hjulet ved drejning mod venstre"
      selector:
        entity:

    target_lights:
      name: "Lamper der skal styres"
      description: "Vælg én eller flere lamper"
      selector:
        target:
          entity:
            domain: light

    scroll_right_direction:
      name: "Handling ved højredrejning"
      description: "Hvad skal der ske ved drejning mod højre?"
      selector:
        select:
          options:
            - label: "Forøg lysstyrke"
              value: "brighten"
            - label: "Reducer lysstyrke"
              value: "dim"
      default: "brighten"

    scroll_left_direction:
      name: "Handling ved venstredrejning"
      description: "Hvad skal der ske ved drejning mod venstre?"
      selector:
        select:
          options:
            - label: "Forøg lysstyrke"
              value: "brighten"
            - label: "Reducer lysstyrke"
              value: "dim"
      default: "dim"

    brightness_per_step_right:
      name: "Lysstyrke pr. trin – Højre (%)"
      default: 5
      selector:
        number:
          min: 1
          max: 20

    brightness_per_step_left:
      name: "Lysstyrke pr. trin – Venstre (%)"
      default: 5
      selector:
        number:
          min: 1
          max: 20

    startup_brightness_right:
      name: "Start-lysstyrke ved tænding – Højre (%)"
      description: "Lysstyrke i %, som lyset tændes med ved højredrejning"
      default: 20
      selector:
        number:
          min: 5
          max: 50

    startup_brightness_left:
      name: "Start-lysstyrke ved tænding – Venstre (%)"
      description: "Lysstyrke i %, som lyset tændes med ved venstredrejning"
      default: 20
      selector:
        number:
          min: 5
          max: 50

trigger:
  - platform: state
    entity_id: !input scrollwheel_right_event_entity
    id: "højre"

  - platform: state
    entity_id: !input scrollwheel_left_event_entity
    id: "venstre"

action:
  - variables:
      er_højre: "{{ trigger.id == 'højre' }}"
      retning_højre: !input scroll_right_direction
      retning_venstre: !input scroll_left_direction
      trin_højre: !input brightness_per_step_right
      trin_venstre: !input brightness_per_step_left
      start_højre: !input startup_brightness_right
      start_venstre: !input startup_brightness_left
      lamper: !input target_lights

      # Bestem retning (+ / -)
      retning: >-
        {% if er_højre %}
          {{ 1 if retning_højre == 'brighten' else -1 }}
        {% else %}
          {{ 1 if retning_venstre == 'brighten' else -1 }}
        {% endif %}

      # Lysændring pr. trigger
      lys_ændring: "{{ (trin_højre if er_højre else trin_venstre) | int * retning }}"

      # Start-lys afhængigt af retning
      start_lys: "{{ start_højre if er_højre else start_venstre }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ retning > 0 }}"
        sequence:
          # Drej op → tænd lampen(e) med start-lys + step
          - service: light.turn_on
            target: "{{ lamper }}"
            data:
              brightness_step_pct: "{{ lys_ændring }}"
              brightness_pct: "{{ start_lys }}"
    default:
      # Drej ned → reducer lysstyrke
      - service: light.turn_on
        target: "{{ lamper }}"
        data:
          brightness_step_pct: "{{ lys_ændring }}"

mode: queued
max: 20

