blueprint:
  name: Ikea_bilresa_scroll_wheel_multi_remoteV2
  description: |
    Blueprint for Ikea Bilresa (button and scroll wheel for 3 different channels)
    Multi-remote enabled version
    Version: 2026-02-13
  domain: automation

  input:
    remotes:
      name: Remotes
      description: One or more Ikea Bilresa scroll wheel remotes
      selector:
        device:
          multiple: true
          filter:
            manufacturer: IKEA of Sweden
            model: BILRESA scroll wheel

    # === CHANNEL 1 ===
    channel1_section:
      name: Channel 1
      collapsed: true
      input:
        click_action_ch1:
          name: "Channel 1: <click> action"
          default: []
          selector:
            action: {}
        double_click_action_ch1:
          name: "Channel 1: <double-click> action"
          default: []
          selector:
            action: {}
        long_click_action_ch1:
          name: "Channel 1: <long-click> action"
          default: []
          selector:
            action: {}
        on_hold_action_ch1:
          name: "Channel 1: <on-hold> action"
          default: []
          selector:
            action: {}
        scroll_wheel_target_ch1:
          name: "Channel 1: Scroll wheel target entity"
          selector:
            entity:
              multiple: true
              filter:
                domain: [light, media_player]
          default: []
        scroll_wheel_mode_ch1:
          name: "Channel 1: Scroll wheel mode"
          default: "lights: dim"
          selector:
            select:
              options:
                - "lights: dim"
                - "lights: color temp and color hue"
                - "lights: color temp only"
                - "lights: color hue only"
                - "media: volume control"
                - "user defined"
        scroll_wheel_mode_ext_ch1:
          name: "Channel 1: Scroll wheel evaluation mode"
          default: "relaxed"
          selector:
            select:
              options: ["relaxed", "instant"]
        scroll_wheel_user_action_ch1:
          name: "Channel 1: User defined scroll wheel action"
          default: []
          selector:
            action: {}

    # === CHANNEL 2 ===
    channel2_section:
      name: Channel 2
      collapsed: true
      input:
        click_action_ch2:
          name: "Channel 2: <click> action"
          default: []
          selector:
            action: {}
        double_click_action_ch2:
          name: "Channel 2: <double-click> action"
          default: []
          selector:
            action: {}
        long_click_action_ch2:
          name: "Channel 2: <long-click> action"
          default: []
          selector:
            action: {}
        on_hold_action_ch2:
          name: "Channel 2: <on-hold> action"
          default: []
          selector:
            action: {}
        scroll_wheel_target_ch2:
          name: "Channel 2: Scroll wheel target entity"
          selector:
            entity:
              multiple: true
              filter:
                domain: [light, media_player]
          default: []
        scroll_wheel_mode_ch2:
          name: "Channel 2: Scroll wheel mode"
          default: "lights: dim"
          selector:
            select:
              options:
                - "lights: dim"
                - "lights: color temp and color hue"
                - "lights: color temp only"
                - "lights: color hue only"
                - "media: volume control"
                - "user defined"
        scroll_wheel_mode_ext_ch2:
          name: "Channel 2: Scroll wheel evaluation mode"
          default: "relaxed"
          selector:
            select:
              options: ["relaxed", "instant"]
        scroll_wheel_user_action_ch2:
          name: "Channel 2: User defined scroll wheel action"
          default: []
          selector:
            action: {}

    # === CHANNEL 3 ===
    channel3_section:
      name: Channel 3
      collapsed: true
      input:
        click_action_ch3:
          name: "Channel 3: <click> action"
          default: []
          selector:
            action: {}
        double_click_action_ch3:
          name: "Channel 3: <double-click> action"
          default: []
          selector:
            action: {}
        long_click_action_ch3:
          name: "Channel 3: <long-click> action"
          default: []
          selector:
            action: {}
        on_hold_action_ch3:
          name: "Channel 3: <on-hold> action"
          default: []
          selector:
            action: {}
        scroll_wheel_target_ch3:
          name: "Channel 3: Scroll wheel target entity"
          selector:
            entity:
              multiple: true
              filter:
                domain: [light, media_player]
          default: []
        scroll_wheel_mode_ch3:
          name: "Channel 3: Scroll wheel mode"
          default: "lights: dim"
          selector:
            select:
              options:
                - "lights: dim"
                - "lights: color temp and color hue"
                - "lights: color temp only"
                - "lights: color hue only"
                - "media: volume control"
                - "user defined"
        scroll_wheel_mode_ext_ch3:
          name: "Channel 3: Scroll wheel evaluation mode"
          default: "relaxed"
          selector:
            select:
              options: ["relaxed", "instant"]
        scroll_wheel_user_action_ch3:
          name: "Channel 3: User defined scroll wheel action"
          default: []
          selector:
            action: {}

    # === GLOBAL SETTINGS ===
    global_setting:
      name: Global settings
      collapsed: true
      input:
        dim_step_pct:
          default: 5
          selector:
            number:
              mode: box
        dim_min_pct:
          default: 5
          selector:
            number:
              mode: box
        min_color_temp:
          default: 2200
          selector:
            number:
              mode: box
        max_color_temp:
          default: 4000
          selector:
            number:
              mode: box
        color_temp_step:
          default: 100
          selector:
            number:
              mode: box
        color_hue_step:
          default: 4
          selector:
            number:
              mode: box
        color_saturation:
          default: 100
          selector:
            number:
              mode: box
        volume_step_pct:
          default: 3.5
          selector:
            number:
              mode: box
        volume_use_up_down_for_instant:
          default: true
          selector:
            boolean:
        volume_max_pct:
          default: 70
          selector:
            number:
              mode: box
        on_hold_delay:
          default: 0.1
          selector:
            number:
              mode: box
              step: 0.1


# ==================== AUTOMATION ====================

alias: Ikea_bilresa_scroll_wheel_multi_remote
mode: queued

trigger:
  - platform: event
    event_type: state_changed

# ==================== VARIABLES ====================

variables:
  var_remotes: !input remotes

  # === CHANNEL 1 ENTITIES ===
  var_button_ch1: >
    {% set out = [] %}
    {% for dev in var_remotes %}
      {% for e in device_entities(dev) %}
        {% if e is match('^event\\..+_3') %}
          {% set out = out + [e] %}
        {% endif %}
      {% endfor %}
    {% endfor %}
    {{ out | list }}

  var_scroll_left_ch1: >
    {% set out = [] %}
    {% for dev in var_remotes %}
      {% for e in device_entities(dev) %}
        {% if e is match('^event\\..+_2') %}
          {% set out = out + [e] %}
        {% endif %}
      {% endfor %}
    {% endfor %}
    {{ out | list }}

  var_scroll_right_ch1: >
    {% set out = [] %}
    {% for dev in var_remotes %}
      {% for e in device_entities(dev) %}
        {% if e is match('^event\\..+_1') %}
          {% set out = out + [e] %}
        {% endif %}
      {% endfor %}
    {% endfor %}
    {{ out | list }}

  var_scroll_left_ext_ch1: >
    {% set out = [] %}
    {% for dev in var_remotes %}
      {% for e in device_entities(dev) %}
        {% if e is match('^sensor\\..+_2') %}
          {% set out = out + [e] %}
        {% endif %}
      {% endfor %}
    {% endfor %}
    {{ out | list }}

  var_scroll_right_ext_ch1: >
    {% set out = [] %}
    {% for dev in var_remotes %}
      {% for e in device_entities(dev) %}
        {% if e is match('^sensor\\..+_1') %}
          {% set out = out + [e] %}
        {% endif %}
      {% endfor %}
    {% endfor %}
    {{ out | list }}


  # === CHANNEL 2 ENTITIES ===
  var_button_ch2: >
    {% set out = [] %}
    {% for dev in var_remotes %}
      {% for e in device_entities(dev) %}
        {% if e is match('^event\\..+_6') %}
          {% set out = out + [e] %}
        {% endif %}
      {% endfor %}
    {% endfor %}
    {{ out | list }}

  var_scroll_left_ch2: >
    {% set out = [] %}
    {% for dev in var_remotes %}
      {% for e in device_entities(dev) %}
        {% if e is match('^event\\..+_5') %}
          {% set out = out + [e] %}
        {% endif %}
      {% endfor %}
    {% endfor %}
    {{ out | list }}

  var_scroll_right_ch2: >
    {% set out = [] %}
    {% for dev in var_remotes %}
      {% for e in device_entities(dev) %}
        {% if e is match('^event\\..+_4') %}
          {% set out = out + [e] %}
        {% endif %}
      {% endfor %}
    {% endfor %}
    {{ out | list }}

  var_scroll_left_ext_ch2: >
    {% set out = [] %}
    {% for dev in var_remotes %}
      {% for e in device_entities(dev) %}
        {% if e is match('^sensor\\..+_5') %}
          {% set out = out + [e] %}
        {% endif %}
      {% endfor %}
    {% endfor %}
    {{ out | list }}

  var_scroll_right_ext_ch2: >
    {% set out = [] %}
    {% for dev in var_remotes %}
      {% for e in device_entities(dev) %}
        {% if e is match('^sensor\\..+_4') %}
          {% set out = out + [e] %}
        {% endif %}
      {% endfor %}
    {% endfor %}
    {{ out | list }}


  # === CHANNEL 3 ENTITIES ===
  var_button_ch3: >
    {% set out = [] %}
    {% for dev in var_remotes %}
      {% for e in device_entities(dev) %}
        {% if e is match('^event\\..+_9') %}
          {% set out = out + [e] %}
        {% endif %}
      {% endfor %}
    {% endfor %}
    {{ out | list }}

  var_scroll_left_ch3: >
    {% set out = [] %}
    {% for dev in var_remotes %}
      {% for e in device_entities(dev) %}
        {% if e is match('^event\\..+_8') %}
          {% set out = out + [e] %}
        {% endif %}
      {% endfor %}
    {% endfor %}
    {{ out | list }}

  var_scroll_right_ch3: >
    {% set out = [] %}
    {% for dev in var_remotes %}
      {% for e in device_entities(dev) %}
        {% if e is match('^event\\..+_7') %}
          {% set out = out + [e] %}
        {% endif %}
      {% endfor %}
    {% endfor %}
    {{ out | list }}

  var_scroll_left_ext_ch3: >
    {% set out = [] %}
    {% for dev in var_remotes %}
      {% for e in device_entities(dev)_
